name: vortex
description: "An app to monitor your turbine and pick the optimal one"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  http: any
  isar: any
  isar_flutter_libs: any
  latlong2: any
  geolocator: any
  osm_geocoder: any
  open_meteo: any
  fl_chart: any
  flutter_location_search: any
  flutter_map: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
