name: vortex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies: 
  latlong2: any
  geolocator: any
  osm_geocoder: any
  open_meteo: any

  http: any
  
  fl_chart: any
  flutter_location_search: any
  flutter_map: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/